CREATE TABLE IF NOT EXISTS quizzes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(191) NULL,
    type VARCHAR(20) NULL,
    start_time DATETIME NULL,
    end_time DATETIME NULL,
    description TEXT NULL,
    max_point INT NULL,
    status VARCHAR(20) NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
